# Generated by Django 4.0.6 on 2022-07-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delete',
            new_name='active',
        ),
    ]
